export const wasteData = {
  recyclable: {
    vi: [
      "giấy",
      "chai",
      "lon",
      "nhựa",
      "bìa",
      "thép",
      "carton",
      "chậu",
      "bao",
      "đĩa",
      "chai thủy tinh",
      "hộp sữa",
      "ly nhựa",
      "hộp giấy",
      "túi nhựa",
      "giấy báo",
      "hộp carton",
      "ly thủy tinh",
      "ống hút",
      "bình nước",
      "bìa cứng",
      "vỏ hộp",
      "chai nước",
      "vỏ lon",
      "bìa cũ",
      "sách cũ",
      "quyển vở",
      "giấy in",
      "đĩa nhựa",
      "chai bia",
      "vỏ chai",
      "ly giấy",
      "giấy carton",
      "chai nhựa",
      "túi giấy",
      "chậu nhựa",
      "tấm nhựa",
      "vỏ sữa",
      "bao bì",
      "bình nhựa",
      "khung nhôm",
      "hộp nhựa",
      "hộp thủy tinh",
      "bình thủy tinh",
      "vỏ chai nhựa",
      "túi vải",
      "tấm thép",
      "ly nhôm",
      "cốc thủy tinh",
      "cốc giấy",
    ],
    ja: [
      "紙",
      "缶",
      "瓶",
      "鉄",
      "アルミ",
      "プラスチック",
      "布",
      "袋",
      "箱",
      "新聞",
      "ガラス瓶",
      "ミルクボックス",
      "プラスチックカップ",
      "紙箱",
      "ビニール袋",
      "新聞紙",
      "段ボール",
      "ガラスコップ",
      "ストロー",
      "ウォーターボトル",
      "硬い段ボール",
      "容器の蓋",
      "飲み物のボトル",
      "アルミ缶",
      "古い段ボール",
      "古い本",
      "ノートブック",
      "プリント紙",
      "プラスチックプレート",
      "ビール瓶",
      "ボトルの蓋",
      "紙コップ",
      "段ボール紙",
      "プラスチックボトル",
      "紙袋",
      "プラスチックの盆栽",
      "プラスチックシート",
      "ミルクの容器",
      "包装材",
      "プラスチックボトル",
      "アルミニウムフレーム",
      "プラスチックケース",
      "ガラスケース",
      "ガラスの瓶",
      "プラスチック蓋",
      "布袋",
      "鉄板",
      "アルミカップ",
      "ガラスコップ",
      "紙の容器",
    ],
    en: [
      "paper",
      "can",
      "bottle",
      "iron",
      "steel",
      "aluminum",
      "plastic",
      "fabric",
      "bag",
      "box",
      "glass bottle",
      "milk box",
      "plastic cup",
      "paper box",
      "plastic bag",
      "newspaper",
      "cardboard",
      "glass cup",
      "straw",
      "water bottle",
      "hard cardboard",
      "container lid",
      "drink bottle",
      "aluminum can",
      "old cardboard",
      "old books",
      "notebook",
      "printing paper",
      "plastic plate",
      "beer bottle",
      "bottle lid",
      "paper cup",
      "cardboard paper",
      "plastic bottle",
      "paper bag",
      "plastic pot",
      "plastic sheet",
      "milk container",
      "packaging material",
      "plastic jug",
      "aluminum frame",
      "plastic case",
      "glass case",
      "glass jar",
      "plastic cover",
      "fabric bag",
      "steel sheet",
      "aluminum cup",
      "glass cup",
      "paper container",
    ],
    mn: [
      "цаас",
      "лааз",
      "шил",
      "төмөр",
      "ган",
      "хөнгөн цагаан",
      "хуванцар",
      "даавуу",
      "уут",
      "хайрцаг",
      "шилэн сав",
      "сүүний хайрцаг",
      "хуванцар аяга",
      "цаасан хайрцаг",
      "гялгар уут",
      "сонин",
      "картон хайрцаг",
      "шилэн аяга",
      "соруула",
      "усны сав",
      "хатуу картон",
      "савны таг",
      "уух сав",
      "хөнгөн цагаан лааз",
      "хуучин хайрцаг",
      "хуучин ном",
      "дэвтэр",
      "хэвлэх цаас",
      "хуванцар таваг",
      "шилэн лонх",
      "лонхны таг",
      "цаасан аяга",
      "картон цаас",
      "хуванцар лонх",
      "цаасан уут",
      "хуванцар сав",
      "хуванцар хуудас",
      "сүүний сав",
      "сав баглаа боодол",
      "хуванцар бариул",
      "хөнгөн цагаан хүрээ",
      "хуванцар хайрцаг",
      "шилэн хайрцаг",
      "шилэн шил",
      "хуванцар таг",
      "даавуун уут",
      "ган хуудас",
      "хөнгөн цагаан аяга",
      "шилэн аяга",
      "цаасан сав",
    ],
    zh: [
      "纸",
      "罐",
      "瓶",
      "铁",
      "钢",
      "铝",
      "塑料",
      "布料",
      "袋子",
      "箱子",
      "玻璃瓶",
      "牛奶盒",
      "塑料杯",
      "纸盒",
      "塑料袋",
      "报纸",
      "硬纸板",
      "玻璃杯",
      "吸管",
      "水瓶",
      "硬纸板箱",
      "容器盖",
      "饮料瓶",
      "铝罐",
      "旧硬纸板",
      "旧书",
      "笔记本",
      "打印纸",
      "塑料盘",
      "啤酒瓶",
      "瓶盖",
      "纸杯",
      "硬纸板纸",
      "塑料瓶",
      "纸袋",
      "塑料盆",
      "塑料片",
      "牛奶容器",
      "包装材料",
      "塑料壶",
      "铝框",
      "塑料盒",
      "玻璃盒",
      "玻璃罐",
      "塑料盖",
      "布袋",
      "钢板",
      "铝杯",
      "玻璃杯",
      "纸容器",
    ],
    url: "../html/usage/usage1.html",
  },
  burnable: {
    vi: [
      "gỗ",
      "lá cây",
      "giấy",
      "bìa cứng",
      "vỏ dừa",
      "bông gòn",
      "vải",
      "xốp",
      "lá chuối",
      "tre",
      "than củi",
      "vỏ trấu",
      "giẻ rách",
      "tăm tre",
      "rơm",
      "cành cây",
      "mùn cưa",
      "lá khô",
      "giấy vệ sinh",
      "vỏ ngô",
      "lá tre",
      "bìa sách",
      "mảnh vải",
      "bông vải",
      "hộp bìa",
      "giấy carton",
      "cành khô",
      "than tổ ong",
      "cành tre",
      "lá rụng",
      "bột gỗ",
      "vỏ cây",
      "tăm xỉa răng",
      "đũa tre",
      "hộp gỗ",
      "hộp quẹt",
      "lá bàng",
      "lá mít",
      "thân cây",
      "thân tre",
      "lá ổi",
      "lá trà",
      "lá táo",
      "lá cọ",
      "lá dứa",
      "rơm rạ",
      "than đen",
      "than trắng",
      "vỏ dưa",
      "xơ dừa",
    ],
    ja: [
      "木",
      "葉っぱ",
      "紙",
      "段ボール",
      "ココナッツの殻",
      "綿",
      "布",
      "発泡スチロール",
      "バナナの葉",
      "竹",
      "木炭",
      "籾殻",
      "ボロ布",
      "竹串",
      "藁",
      "枝",
      "おがくず",
      "枯れ葉",
      "トイレットペーパー",
      "トウモロコシの皮",
      "竹の葉",
      "本のカバー",
      "布の切れ端",
      "綿の布",
      "箱の段ボール",
      "紙の段ボール",
      "乾いた枝",
      "炭のブリケット",
      "竹の枝",
      "落ち葉",
      "木粉",
      "樹皮",
      "爪楊枝",
      "竹の箸",
      "木箱",
      "ライター",
      "バナナの葉",
      "みかんの皮",
      "木の幹",
      "竹の幹",
      "お茶の葉",
      "リンゴの葉",
      "ヤシの葉",
      "パイナップルの葉",
      "稲わら",
      "黒炭",
      "白炭",
      "スイカの皮",
      "ココナッツ繊維",
    ],
    en: [
      "wood",
      "leaves",
      "paper",
      "cardboard",
      "coconut shell",
      "cotton",
      "fabric",
      "foam",
      "banana leaves",
      "bamboo",
      "charcoal",
      "rice husk",
      "rag",
      "bamboo stick",
      "straw",
      "branches",
      "sawdust",
      "dry leaves",
      "toilet paper",
      "corn husk",
      "bamboo leaves",
      "book cover",
      "fabric scrap",
      "cotton fabric",
      "box cardboard",
      "carton paper",
      "dry branches",
      "coal briquette",
      "bamboo branch",
      "fallen leaves",
      "wood powder",
      "bark",
      "toothpick",
      "bamboo chopsticks",
      "wooden box",
      "lighter",
      "mango leaves",
      "banana peel",
      "tree trunk",
      "bamboo trunk",
      "tea leaves",
      "apple leaves",
      "palm leaves",
      "pineapple leaves",
      "straw bundles",
      "black coal",
      "white coal",
      "watermelon rind",
      "coconut fiber",
    ],
    mn: [
      "мод",
      "навч",
      "цаас",
      "картон",
      "кокосын хальс",
      "хөвөн",
      "даавуу",
      "хөөсөнцөр",
      "бананы навч",
      "хулс",
      "нүүрс",
      "будааны хальс",
      "хувцасны өөдөс",
      "хулсны савх",
      "үрэл",
      "модны мөчир",
      "модны үртэс",
      "хуурай навч",
      "ариун цэврийн цаас",
      "эрдэнэ шишийн хальс",
      "хулсны навч",
      "номны хавтас",
      "даавууны өөдөс",
      "хөвөн даавуу",
      "хайрцаг картон",
      "цаасан хайрцаг",
      "хуурай мөчир",
      "нүүрсний шахмал",
      "хулсны мөчир",
      "унасан навч",
      "модны нунтаг",
      "модны холтос",
      "шүдний чигчлүүр",
      "хулсны савх",
      "модон хайрцаг",
      "зай хураагуур",
      "гадилын хальс",
      "модны их бие",
      "хулсны их бие",
      "цайны навч",
      "алимны навч",
      "дал модны навч",
      "ананасын навч",
      "үр тарианы сав",
      "хар нүүрс",
      "цагаан нүүрс",
      "тарвасны хальс",
      "кокосын ширхэг",
    ],
    zh: [
      "木头",
      "树叶",
      "纸",
      "硬纸板",
      "椰壳",
      "棉花",
      "布料",
      "泡沫",
      "香蕉叶",
      "竹子",
      "木炭",
      "稻壳",
      "破布",
      "竹签",
      "稻草",
      "树枝",
      "锯末",
      "干叶",
      "卫生纸",
      "玉米皮",
      "竹叶",
      "书皮",
      "布片",
      "棉布",
      "纸箱",
      "纸盒",
      "干树枝",
      "煤球",
      "竹枝",
      "落叶",
      "木粉",
      "树皮",
      "牙签",
      "竹筷",
      "木箱",
      "打火机",
      "芒果叶",
      "香蕉皮",
      "树干",
      "竹干",
      "茶叶",
      "苹果叶",
      "棕榈叶",
      "菠萝叶",
      "稻草束",
      "黑炭",
      "白炭",
      "西瓜皮",
      "椰壳纤维",
    ],
    url: "../html/usage/usage2.html",
  },
  nonBurnable: {
    vi: [
      "thủy tinh",
      "kim loại",
      "chai thủy tinh",
      "gương",
      "đinh",
      "ốc vít",
      "dao",
      "đĩa sứ",
      "gạch",
      "pin",
      "bóng đèn",
      "lon nhôm",
      "vật dụng inox",
      "đồ chơi kim loại",
      "đồng hồ",
      "thiết bị điện tử",
      "bàn phím",
      "đĩa CD",
      "dây điện",
      "bình chữa cháy",
      "vỏ bình ga",
      "máy ảnh",
      "mạch điện",
      "loa",
      "bàn là",
      "bộ sạc",
      "máy phát điện",
      "máy in",
      "đèn LED",
      "vỏ bóng đèn",
      "ống nhôm",
      "khung thép",
      "vỏ đồng hồ",
      "dây cáp",
      "cánh quạt kim loại",
      "máy mài",
      "máy khoan",
      "chân đèn",
      "khay sắt",
      "thùng inox",
      "kéo",
      "đinh tán",
      "máy hút bụi",
      "máy chiếu",
      "vỏ điện thoại",
      "lò vi sóng",
      "máy sấy",
      "cửa kim loại",
      "lồng sắt",
      "khóa cửa",
    ],
    ja: [
      "ガラス",
      "金属",
      "ガラス瓶",
      "鏡",
      "釘",
      "ネジ",
      "ナイフ",
      "陶器の皿",
      "レンガ",
      "電池",
      "電球",
      "アルミ缶",
      "ステンレス製品",
      "金属製のおもちゃ",
      "時計",
      "電子機器",
      "キーボード",
      "CDディスク",
      "電線",
      "消火器",
      "ガスボンベの殻",
      "カメラ",
      "電子回路",
      "スピーカー",
      "アイロン",
      "充電器",
      "発電機",
      "プリンター",
      "LEDライト",
      "電球の殻",
      "アルミパイプ",
      "鉄枠",
      "時計ケース",
      "ケーブル",
      "金属羽根",
      "研磨機",
      "ドリル",
      "スタンドランプ",
      "鉄製トレイ",
      "ステンレスバケツ",
      "ハサミ",
      "リベット",
      "掃除機",
      "プロジェクター",
      "携帯電話のカバー",
      "電子レンジ",
      "ヘアドライヤー",
      "金属製のドア",
      "鉄のケージ",
      "ドアロック",
    ],
    en: [
      "glass",
      "metal",
      "glass bottle",
      "mirror",
      "nail",
      "screw",
      "knife",
      "ceramic plate",
      "brick",
      "battery",
      "light bulb",
      "aluminum can",
      "stainless steel items",
      "metal toys",
      "watch",
      "electronic device",
      "keyboard",
      "CD disk",
      "electric wire",
      "fire extinguisher",
      "gas cylinder shell",
      "camera",
      "circuit board",
      "speaker",
      "iron",
      "charger",
      "generator",
      "printer",
      "LED lamp",
      "bulb cover",
      "aluminum pipe",
      "steel frame",
      "watch case",
      "cable",
      "metal blade",
      "grinding machine",
      "drill",
      "lamp stand",
      "iron tray",
      "stainless bucket",
      "scissors",
      "rivet",
      "vacuum cleaner",
      "projector",
      "phone case",
      "microwave oven",
      "hair dryer",
      "metal door",
      "iron cage",
      "door lock",
    ],
    mn: [
      "шил",
      "металл",
      "шилэн сав",
      "толь",
      "хадаас",
      "эрэг боолт",
      "хутга",
      "шаазан таваг",
      "тоосго",
      "зай",
      "гэрлийн чийдэн",
      "хөнгөн цагаан лааз",
      "зэвэрдэггүй ган эдлэл",
      "металл тоглоом",
      "цаг",
      "цахилгаан хэрэгсэл",
      "гарны товчлуур",
      "CD диск",
      "цахилгааны утас",
      "гал унтраагч",
      "хийн цилиндрийн бүрхүүл",
      "камер",
      "цахилгаан хэлхээ",
      "чанга яригч",
      "индүү",
      "цэнэглэгч",
      "генератор",
      "хэвлэгч",
      "LED гэрэл",
      "чийдэнгийн бүрхүүл",
      "хөнгөн цагаан хоолой",
      "төмөр хүрээ",
      "цагны хайрцаг",
      "кабель",
      "металл ир",
      "үрэгч машин",
      "өрөм",
      "гэрлийн суурь",
      "төмөр тавиур",
      "зэвэрдэггүй ган хувин",
      "хайч",
      "арматур",
      "тоос сорогч",
      "проектор",
      "утасны бүрхүүл",
      "микро долгионы зуух",
      "үс хатаагч",
      "төмөр хаалга",
      "төмөр тор",
      "хаалганы цоож",
    ],
    zh: [
      "玻璃",
      "金属",
      "玻璃瓶",
      "镜子",
      "钉子",
      "螺丝",
      "刀",
      "陶瓷盘",
      "砖块",
      "电池",
      "灯泡",
      "铝罐",
      "不锈钢用品",
      "金属玩具",
      "手表",
      "电子设备",
      "键盘",
      "光盘",
      "电线",
      "灭火器",
      "煤气罐壳",
      "相机",
      "电路板",
      "扬声器",
      "熨斗",
      "充电器",
      "发电机",
      "打印机",
      "LED灯",
      "灯泡罩",
      "铝管",
      "钢框架",
      "手表盒",
      "电缆",
      "金属刀片",
      "磨床",
      "钻头",
      "灯座",
      "铁托盘",
      "不锈钢桶",
      "剪刀",
      "铆钉",
      "吸尘器",
      "投影仪",
      "手机壳",
      "微波炉",
      "吹风机",
      "金属门",
      "铁笼子",
      "门锁",
    ],
    url: "../html/usage/usage3.html",
  },
  oversized: {
    vi: [
      "tủ lạnh",
      "máy giặt",
      "giường",
      "sofa",
      "tủ quần áo",
      "bàn làm việc",
      "tủ gỗ",
      "ghế gỗ",
      "kệ sách",
      "bàn ăn",
      "tủ bếp",
      "kệ tivi",
      "bàn họp",
      "giá treo đồ",
      "ghế massage",
      "bàn phím lớn",
      "máy tập thể dục",
      "bồn tắm",
      "cửa lớn",
      "máy chạy bộ",
    ],
    ja: [
      "冷蔵庫",
      "洗濯機",
      "ベッド",
      "ソファ",
      "洋服ダンス",
      "机",
      "木製キャビネット",
      "木製椅子",
      "本棚",
      "ダイニングテーブル",
      "キッチンキャビネット",
      "テレビ台",
      "会議机",
      "コートハンガー",
      "マッサージチェア",
      "大型キーボード",
      "エクササイズマシン",
      "浴槽",
      "大きな扉",
      "ランニングマシン",
    ],
    en: [
      "refrigerator",
      "washing machine",
      "bed",
      "sofa",
      "wardrobe",
      "desk",
      "wooden cabinet",
      "wooden chair",
      "bookshelf",
      "dining table",
      "kitchen cabinet",
      "TV stand",
      "conference table",
      "clothes rack",
      "massage chair",
      "large keyboard",
      "exercise machine",
      "bathtub",
      "large door",
      "treadmill",
    ],
    mn: [
      "хөргөгч",
      "угаалгын машин",
      "ор",
      "буйдан",
      "хувцасны шүүгээ",
      "ширээ",
      "модон шүүгээ",
      "модон сандал",
      "номын тавиур",
      "хоолны ширээ",
      "гал тогооны шүүгээ",
      "телевизийн тавиур",
      "хурлын ширээ",
      "хувцасны өлгүүр",
      "массажны сандал",
      "том гар",
      "дасгалын төхөөрөмж",
      "ванн",
      "том хаалга",
      "гүйлтийн зам",
    ],
    zh: [
      "冰箱",
      "洗衣机",
      "床",
      "沙发",
      "衣柜",
      "书桌",
      "木柜",
      "木椅",
      "书架",
      "餐桌",
      "厨房柜",
      "电视柜",
      "会议桌",
      "衣架",
      "按摩椅",
      "大键盘",
      "健身器材",
      "浴缸",
      "大门",
      "跑步机",
    ],
    url: "../html/usage/usage3.html",
  },
  appliances: {
    vi: [
      "máy sấy tóc",
      "bàn là",
      "lò vi sóng",
      "máy xay sinh tố",
      "máy pha cà phê",
      "bếp điện",
      "máy hút mùi",
      "máy làm bánh",
      "máy hâm sữa",
      "máy nướng bánh mì",
      "máy lọc nước",
      "máy ép hoa quả",
      "máy rửa bát",
      "máy đánh trứng",
      "máy hút bụi",
      "máy xay tiêu",
      "máy hâm nước",
      "quạt hơi nước",
      "máy lạnh",
      "bếp từ",
    ],
    ja: [
      "ヘアドライヤー",
      "アイロン",
      "電子レンジ",
      "ミキサー",
      "コーヒーメーカー",
      "電気コンロ",
      "換気扇",
      "パン焼き機",
      "哺乳瓶ウォーマー",
      "トースター",
      "浄水器",
      "ジューサー",
      "食器洗い機",
      "泡立て器",
      "掃除機",
      "ペッパーミル",
      "湯沸かしポット",
      "蒸気ファン",
      "エアコン",
      "IHコンロ",
    ],
    en: [
      "hair dryer",
      "iron",
      "microwave oven",
      "blender",
      "coffee maker",
      "electric stove",
      "range hood",
      "bread maker",
      "bottle warmer",
      "toaster",
      "water purifier",
      "juicer",
      "dishwasher",
      "egg beater",
      "vacuum cleaner",
      "pepper grinder",
      "water heater",
      "steam fan",
      "air conditioner",
      "induction cooker",
    ],
    mn: [
      "үс хатаагч",
      "индүү",
      "микро долгионы зуух",
      "холигч",
      "кофе чанагч",
      "цахилгаан зуух",
      "агаар сорогч",
      "талх шарагч",
      "хүүхдийн сав халаагч",
      "талх шарагч",
      "ус цэвэршүүлэгч",
      "жимсний шүүс шахагч",
      "сав угаагч машин",
      "өндөг хольдог машин",
      "тоос сорогч",
      "перец нунтаглагч",
      "ус халаагч",
      "уурын сэнс",
      "агааржуулагч",
      "индукцийн зуух",
    ],
    zh: [
      "吹风机",
      "熨斗",
      "微波炉",
      "搅拌机",
      "咖啡机",
      "电炉",
      "抽油烟机",
      "面包机",
      "奶瓶加热器",
      "烤面包机",
      "净水器",
      "榨汁机",
      "洗碗机",
      "打蛋器",
      "吸尘器",
      "胡椒研磨器",
      "热水壶",
      "蒸汽风扇",
      "空调",
      "电磁炉",
    ],
    url: "../html/usage/usage3.html",
  },
  electronics: {
    vi: [
      "máy tính",
      "điện thoại",
      "tivi",
      "máy ảnh",
      "máy in",
      "máy chiếu",
      "loa",
      "máy nghe nhạc",
      "bộ phát wifi",
      "đồng hồ thông minh",
      "máy quét mã vạch",
      "máy ghi âm",
      "máy chơi game",
      "bộ định tuyến",
      "màn hình máy tính",
      "máy tính bảng",
      "máy lạnh mini",
      "tai nghe",
      "máy chơi đĩa DVD",
      "camera an ninh",
    ],
    ja: [
      "コンピュータ",
      "携帯電話",
      "テレビ",
      "カメラ",
      "プリンター",
      "プロジェクター",
      "スピーカー",
      "音楽プレーヤー",
      "Wi-Fiルーター",
      "スマートウォッチ",
      "バーコードスキャナー",
      "録音機",
      "ゲーム機",
      "ルーター",
      "コンピュータモニター",
      "タブレット",
      "ミニエアコン",
      "イヤホン",
      "DVDプレーヤー",
      "セキュリティカメラ",
    ],
    en: [
      "computer",
      "phone",
      "TV",
      "camera",
      "printer",
      "projector",
      "speaker",
      "music player",
      "Wi-Fi router",
      "smartwatch",
      "barcode scanner",
      "voice recorder",
      "game console",
      "router",
      "monitor",
      "tablet",
      "mini air conditioner",
      "headphones",
      "DVD player",
      "security camera",
    ],
    mn: [
      "компьютер",
      "утас",
      "телевизор",
      "камер",
      "хэвлэгч",
      "проектор",
      "чанга яригч",
      "хөгжим тоглуулагч",
      "Wi-Fi чиглүүлэгч",
      "ухаалаг цаг",
      "баркод уншигч",
      "дуу бичигч",
      "тоглоомын консол",
      "чиглүүлэгч",
      "компьютерийн дэлгэц",
      "таблет",
      "мини агааржуулагч",
      "чихэвч",
      "DVD тоглуулагч",
      "аюулгүй байдлын камер",
    ],
    zh: [
      "电脑",
      "手机",
      "电视",
      "相机",
      "打印机",
      "投影仪",
      "扬声器",
      "音乐播放器",
      "无线路由器",
      "智能手表",
      "条形码扫描器",
      "录音机",
      "游戏机",
      "路由器",
      "显示器",
      "平板电脑",
      "迷你空调",
      "耳机",
      "DVD播放器",
      "安全摄像头",
    ],
    url: "../html/usage/usage3.html",
  },
};
