// wasteData.js

export const wasteData = {
  recyclable: {
    vi: [
      "giấy",
      "chai",
      "lon",
      "nhựa",
      "bìa",
      "thép",
      "carton",
      "chậu",
      "bao",
      "đĩa",
    ],
    ja: [
      "紙",
      "缶",
      "瓶",
      "鉄",
      "アルミ",
      "プラスチック",
      "布",
      "袋",
      "箱",
      "新聞",
    ],
    en: [
      "paper",
      "can",
      "bottle",
      "iron",
      "steel",
      "aluminum",
      "plastic",
      "fabric",
      "bag",
      "box",
    ],
    mn: [
      "цаас",
      "лааз",
      "шил",
      "төмөр",
      "ган",
      "хөнгөн цагаан",
      "хуванцар",
      "даавуу",
      "уут",
      "хайрцаг",
    ],
    url: "../html/usage/usage1.html",
  },
  burnable: {
    vi: [
      "gỗ",
      "lá cây",
      "giấy",
      "bìa cứng",
      "vỏ dừa",
      "bông gòn",
      "vải",
      "xốp",
      "lá chuối",
      "tre",
      "than củi",
      "vỏ trấu",
      "giẻ rách",
      "tăm tre",
      "rơm",
      "cành cây",
      "mùn cưa",
      "lá khô",
      "giấy vệ sinh",
      "vỏ ngô",
    ],
    ja: [
      "木",
      "葉っぱ",
      "紙",
      "段ボール",
      "ココナッツの殻",
      "綿",
      "布",
      "発泡スチロール",
      "バナナの葉",
      "竹",
      "木炭",
      "籾殻",
      "ボロ布",
      "竹串",
      "藁",
      "枝",
      "おがくず",
      "枯れ葉",
      "トイレットペーパー",
      "トウモロコシの皮",
    ],
    en: [
      "wood",
      "leaves",
      "paper",
      "cardboard",
      "coconut shell",
      "cotton",
      "fabric",
      "foam",
      "banana leaves",
      "bamboo",
      "charcoal",
      "rice husk",
      "rag",
      "bamboo stick",
      "straw",
      "branches",
      "sawdust",
      "dry leaves",
      "toilet paper",
      "corn husk",
    ],
    mn: [
      "мод",
      "навч",
      "цаас",
      "картон",
      "кокосын хальс",
      "хөвөн",
      "даавуу",
      "хөөсөнцөр",
      "бананы навч",
      "хулс",
      "нүүрс",
      "будааны хальс",
      "хувцасны өөдөс",
      "хулсны савх",
      "үрэл",
      "модны мөчир",
      "модны үртэс",
      "хуурай навч",
      "ариун цэврийн цаас",
      "эрдэнэ шишийн хальс",
    ],
    url: "../html/usage/usage2.html",
  },
  nonBurnable: {
    vi: [
      "thủy tinh",
      "kim loại",
      "chai thủy tinh",
      "gương",
      "đinh",
      "ốc vít",
      "dao",
      "đĩa sứ",
      "gạch",
      "pin",
      "bóng đèn",
      "lon nhôm",
      "vật dụng inox",
      "đồ chơi kim loại",
      "đồng hồ",
      "thiết bị điện tử",
      "bàn phím",
      "đĩa CD",
      "dây điện",
      "bình chữa cháy",
    ],
    ja: [
      "ガラス",
      "金属",
      "ガラス瓶",
      "鏡",
      "釘",
      "ネジ",
      "ナイフ",
      "陶器の皿",
      "レンガ",
      "電池",
      "電球",
      "アルミ缶",
      "ステンレス製品",
      "金属製のおもちゃ",
      "時計",
      "電子機器",
      "キーボード",
      "CDディスク",
      "電線",
      "消火器",
    ],
    en: [
      "glass",
      "metal",
      "glass bottle",
      "mirror",
      "nail",
      "screw",
      "knife",
      "ceramic plate",
      "brick",
      "battery",
      "light bulb",
      "aluminum can",
      "stainless steel items",
      "metal toys",
      "watch",
      "electronic device",
      "keyboard",
      "CD disk",
      "electric wire",
      "fire extinguisher",
    ],
    mn: [
      "шил",
      "металл",
      "шилэн сав",
      "толь",
      "хадаас",
      "эрэг боолт",
      "хутга",
      "шаазан таваг",
      "тоосго",
      "зай",
      "гэрлийн чийдэн",
      "хөнгөн цагаан лааз",
      "зэвэрдэггүй ган эдлэл",
      "металл тоглоом",
      "цаг",
      "цахилгаан хэрэгсэл",
      "гарны товчлуур",
      "CD диск",
      "цахилгааны утас",
      "гал унтраагч",
    ],
    url: "../html/usage/usage3.html",
  },
  oversized: {
    vi: ["tủ lạnh", "máy giặt"],
    ja: ["冷蔵庫", "洗濯機"],
    en: ["refrigerator", "washing machine"],
    mn: ["хөргөгч", "угаалгын машин"],
    url: "../html/usage/usage3.html",
  },
  appliances: {
    vi: ["máy sấy tóc", "bàn là"],
    ja: ["ヘアドライヤー", "アイロン"],
    en: ["hair dryer", "iron"],
    mn: ["үс хатаагч", "индүү"],
    url: "../html/usage/usage3.html",
  },
  electronics: {
    vi: ["máy tính", "điện thoại"],
    ja: ["コンピュータ", "携帯電話"],
    en: ["computer", "phone"],
    mn: ["компьютер", "утас"],
    url: "../html/usage/usage3.html",
  },
};
